# Generated by Django 3.1 on 2021-03-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('description', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Serviceitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('icon', models.CharField(default='la la-bar-chart', max_length=600)),
                ('mini_description', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0)),
                ('service', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.service')),
            ],
        ),
    ]
