# Generated by Django 3.1 on 2021-03-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210319_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='mini_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
