# Generated by Django 3.1 on 2021-03-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210320_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='team_member',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='team_member',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='team_member',
            name='first_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='team_member',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='team_member',
            name='last_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='team_member',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='team_member',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('quality', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team_member')),
            ],
        ),
        migrations.AddField(
            model_name='team_member',
            name='developer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.developer'),
        ),
    ]
