# Generated by Django 3.1 on 2021-03-21 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210320_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='upload'),
        ),
        migrations.CreateModel(
            name='Itemservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_description', models.CharField(max_length=1000)),
                ('status', models.IntegerField(default=0)),
                ('serviceitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.serviceitem')),
            ],
        ),
    ]
