# Generated by Django 3.1 on 2021-05-09 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_experience_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('mini_description', models.CharField(max_length=500)),
                ('link', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(blank=True)),
                ('member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.team_member')),
            ],
        ),
    ]
