# Generated by Django 3.1 on 2021-05-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=1000)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
